translate_task:
  description: Translate {sentence} from English to Italian without make mistakes.
  expected_output: A well formatted tranlation from English to Italian using proper capitalization of names and places.
  agent: translator_agent

retranslate_task:
  description: Translate {sentence} from Italian to Korean without make mistakes.
  expected_output: A well formatted tranlation from Italian to Korean using proper capitalization of names and places.
  agent: translator_agent

count_task:
  description: Count the amount of letters in a sentence.
  expected_output: The number of letters in a sentence.
  agent: counter_agent
